spring.application.name=Chaotic_Deck
spring.datasource.url=jdbc:postgresql://aws-0-ap-south-1.pooler.supabase.com:6543/postgres
spring.datasource.username=postgres.jemuzbndkxlvxidajdpr
spring.datasource.password=UKJmvwzD06DYQ1bTUKJmvwzD06DYQ1bT

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# สั่งให้ Spring Boot รันไฟล์ schema.sql อัตโนมัติ (แม้ไม่ใช่ Database แบบฝังตัว)
spring.sql.init.mode=always
