spring.application.name=Chaotic_Deck
spring.datasource.url=jdbc:postgresql://aws-0-ap-south-1.pooler.supabase.com:6543/postgres
spring.datasource.username=postgres.jemuzbndkxlvxidajdpr
spring.datasource.password=UKJmvwzD06DYQ1bTUKJmvwzD06DYQ1bT

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


